### ISSUE TITLE
v1.0.25 Fails to save pixel based point spectra

### ISSUE THREAD

**Issue by xrftrevor** [NSLS-II/PyXRF#316]
BUG significant issue: In MAP fitting **Save spectra for pixels in the selected region** no longer works
## Expected Behavior

Files are save with pixel spectra.

Create plot window with individual spectra.
## Current Behavior

Error
Failed to Fit Individual Pixel Spectra X -> 'Fit1D' object has no attribute 'hdfpath'

If not asking for Save spectra.... the map is generated.
## Possible Solution

**This worked fine in earlier version v1.0.17** other versions between 25 not tested.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Your Environment

W11 -> miniconda -> conda install

**Comment by dmgav** [comment]
@xrftrevor Could you please outline the steps to reproduce the issue in more detail. I could not reproduce the issue at the first attempt.

**Comment by xrftrevor** [comment]
1.  Read in data - set default directory then read in a file.
  2.  Model - Read in Model parameter file
     *   General set the energy window
     *   Start fitting
  3.  Maps
     *   Start XRF Map Fitting
     *   Set XY scale to positions (this is an unrelated bug in that it needs to be reset after each map fitting even though the button label will stated positions)
     *   Click safe spectra for pixels

                                                              i.      End row 15

                                                             ii.      Start row 15

                                                           iii.      End Column 31

                                                           iv.      Start XRF Map Fitting
***@***.***
***@***.***

The spectra use to be written to a directory,
Scan2d_<filename>_pixel_fit

I hope this helps. I have used an older version for my current critical analysis to check to see if the detailed fits make sense.

Thank you,

Dennis J. Trevor
Tech Manager
***@***.***
Your Optical Fiber Solutions Partner(tm)
19 Schoolhouse Rd. | Somerset, NJ 08873
Office: 732 748 7488
Mobile: 908 385 9597

www.ofsoptics.com<https://urldefense.com/v3/__http:/www.ofsoptics.com/__;!!P4SdNyxKAPE!CRMT-FEL8_NwFLKcOfpDM53SiP-NTLE3Ns8DZpqjTzreoBK7-zfX3JzbaFIH1HrgBvLF47NtIJaGbQ$>

**Comment by dmgav** [comment]
Thanks @xrftrevor I fixed both bugs. The fix will be included in v1.0.27. You can also pip-install the fixed version from GitHub.

**Comment by xrftrevor** [comment]
Thank you, I will upgrade.

Dennis

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
